name = "yass"
description = "Static website generator"
version = "3.1.0"

authors = ["AJ Ianozi"]
maintainers = ["AJ Ianozi <aj@ianozi.com>"]
maintainers-logins = ["AJ-Ianozi"]
licenses = "GPL-3.0-or-later"
website = "https://yass.website"
tags = ["web", "markdown", "generator"]

executables = ["yass"]


[gpr-externals]
YASS_OS = ["Windows", "Unix"]
Mode = ["dev", "debug", "release", "analyze"]

[gpr-set-externals]
Mode = "release"

[gpr-set-externals.'case(os)']
  windows = { YASS_OS = "Windows" }
  '...'   = { YASS_OS = "Unix" }

[[depends-on]]
aws = "^24.0.0"
xmlada = "^24.0.0"
gnatcoll = "^24.0.0"
libcmark = ">=0.0.1"
