name = "yass"
description = "Static website generator"
version = "3.2.0-dev"

long-description = '''
Yass is static site generator written in Ada. It is *headless*
application (no user interface).

## Features
* Support almost infinite amount of custom tags in HTML templates
* Separated tags for whole site and each page
* Fast
* Can be extended with modules written in any script/programming language
* Generating sitemaps
* Generating Atom feeds
* Auto reconfigure server when configuration file was changed
'''

authors = ["AJ Ianozi"]
maintainers = ["AJ Ianozi <aj@ianozi.com>"]
maintainers-logins = ["AJ-Ianozi"]
licenses = "GPL-3.0-or-later"
website = "https://yass.website"
tags = ["web", "markdown", "generator"]

executables = ["yass"]


[gpr-externals]
YASS_OS = ["Windows", "Unix"]
Mode = ["dev", "debug", "release", "analyze"]

[gpr-set-externals]
Mode = "release"

[gpr-set-externals.'case(os)']
  windows = { YASS_OS = "Windows" }
  '...'   = { YASS_OS = "Unix" }

[[depends-on]]
libcmark = ">=0.0.1"

[[depends-on]]
resources = "~0.1.0"

# See https://github.com/AdaCore/aws/issues/380
# and https://github.com/alire-project/alire/issues/1710
[depends-on.'case(os)'.windows]
aws = "^23.0.0"
xmlada = "^23.0.0"
gnatcoll = "^23.0.0"

[depends-on.'case(os)'.'...']
aws = "^24.0.0"
xmlada = "^24.0.0"
gnatcoll = "^24.0.0"
