name: Continuous Integration

on: pull_request

### Until I get the new tests working I will have to just deal with this method.

jobs:
  ###  x86-64 linux
  build-linux_x86_64:

    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up alire
      uses: alire-project/setup-alire@v3

    - name: Build yass
      run: >
        alr -n update &&
        alr -n build --release

    - name: Test yass
      run: >
        bin/yass build docs/user &&
        bin/yass createnow newsite &&
        bin/yass build newsite

  ###  x86-64 MacOS
  build-macos_x86_64:
    runs-on: macos-13

    steps: 
    
      - name: Checkout
        uses: actions/checkout@v3

      - name: install latest xcode stuff
        uses: maxim-lobanov/setup-xcode@v1
        with:
           xcode-version: latest-stable

      - name: Set up alire
        uses: alire-project/setup-alire@v3

      - name: Build yass
        run: >
          alr -n update &&
          alr -n build --release

      - name: Test yass
        run: >
          bin/yass build docs/user &&
          bin/yass createnow newsite &&
          bin/yass build newsite

  ###  build on windows
  build-windows:
    runs-on: windows-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up alire
        uses: alire-project/setup-alire@v3

      - name: Build yass
        run: >
          alr -n update &&
          alr -n build --release


      - name: Test yass
        run: >
          bin/yass build docs/user &&
          bin/yass createnow newsite &&
          bin/yass build newsite
