name: Build Release
on:
   workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up GNAT toolchain
      run: >
        sudo apt-get update &&
        sudo apt-get install gnat gprbuild libcmark-dev libaws* libxmlada*

    - name: Build
      run: gprbuild -XMode=release

    - name: Compress yass
      run: zip -r yass-linux_x86_64.zip bin

    - name: Upload yass
      uses: actions/upload-artifact@v2
      with:
         name: yass-linux_x86_64.zip
         path: yass-linux_x86_64.zip
